services:
  pg:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 3s
      timeout: 3s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - foodize-network

  rabbitmq:
    image: rabbitmq:4-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-foodize}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-foodize}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST:-foodize}
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - foodize-network

  redis:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - foodize-network

  migrations:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
      target: migrations
    volumes:
      - ./src/backend:/backend
    env_file:
      - .env
    depends_on:
      pg:
        condition: service_healthy
    environment:
      DB_URL: ${DB__URL}
    restart: "no"
    networks:
      - foodize-network

  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
      target: backend
    env_file:
      - .env
    depends_on:
      migrations:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      DB_URL: ${DB__URL}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
      RABBITMQ__URL: ${RABBITMQ__URL:-amqp://foodize:foodize@rabbitmq:5672/foodize}
      WATCHFILES_FORCE_POLLING: "true"
    ports:
      - "8000:8000"
    volumes:
      - ./src/backend:/backend
    networks:
      - foodize-network

  worker:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
      target: worker
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ__URL: ${RABBITMQ__URL:-amqp://foodize:foodize@rabbitmq:5672/foodize}
      WATCHFILES_FORCE_POLLING: "true"
    volumes:
      - ./src/backend:/backend
    networks:
      - foodize-network

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
      target: dev
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./src/frontend:/frontend
      - /frontend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    networks:
      - foodize-network

volumes:
  pgdata:

networks:
  foodize-network:
