"""add prep time

Revision ID: 8d8104b7b6c3
Revises: e5f6a7b8c9d0
Create Date: 2026-04-18 17:40:30.374161

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8d8104b7b6c3"
down_revision: Union[str, Sequence[str], None] = "e5f6a7b8c9d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "menu_items",
        sa.Column("prep_time_minutes", sa.Integer(), server_default="15", nullable=False),
    )
    op.drop_index(op.f("ix_order_events_order_id"), table_name="order_events")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_order_events_order_id"), "order_events", ["order_id"], unique=False)
    op.drop_column("menu_items", "prep_time_minutes")
    # ### end Alembic commands ###
