"""add staff system and update relationships

Revision ID: 9b90b58867ed
Revises: f46678e8cada
Create Date: 2026-04-10 15:55:30.352814

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9b90b58867ed"
down_revision: Union[str, Sequence[str], None] = "f46678e8cada"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "staff_requests",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("restaurant_id", sa.UUID(), nullable=False),
        sa.Column("message", sa.String(length=500), nullable=True),
        sa.Column("status", sa.String(), server_default="PENDING", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["restaurant_id"],
            ["restaurants.id"],
            name=op.f("fk_staff_requests_restaurant_id_restaurants"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_staff_requests_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_staff_requests")),
    )
    op.create_index(op.f("ix_staff_requests_id"), "staff_requests", ["id"], unique=False)
    op.add_column(
        "staff_profiles", sa.Column("role", sa.String(), server_default="COOK", nullable=False)
    )
    op.drop_column("staff_profiles", "is_on_shift")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "staff_profiles",
        sa.Column(
            "is_on_shift",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("staff_profiles", "role")
    op.drop_index(op.f("ix_staff_requests_id"), table_name="staff_requests")
    op.drop_table("staff_requests")
    # ### end Alembic commands ###
