"""remove_description_from_vendor_profiles

Revision ID: b5dcc8a302c6
Revises: f3a4b5c6d7e8
Create Date: 2026-05-02 20:26:54.990840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5dcc8a302c6'
down_revision: Union[str, Sequence[str], None] = 'f3a4b5c6d7e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vendor_profiles", "description")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vendor_profiles",
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
