"""add password фand remove enum

Revision ID: e18f2e2cae9a
Revises: ab4a0323c953
Create Date: 2026-03-25 13:38:17.107493

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e18f2e2cae9a"
down_revision: Union[str, Sequence[str], None] = "ab4a0323c953"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "menus",
        "category",
        existing_type=postgresql.ENUM("SHAURMA", "DRINK", "OTHER", name="category"),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.add_column("users", sa.Column("hashed_password", sa.String(), nullable=False))
    op.alter_column(
        "users",
        "user_role",
        existing_type=postgresql.ENUM("CUSTOMER", "VENDOR", "ADMIN", name="userrole"),
        type_=sa.String(),
        existing_nullable=False,
        existing_server_default=sa.text("'CUSTOMER'::userrole"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "user_role",
        existing_type=sa.String(),
        type_=postgresql.ENUM("CUSTOMER", "VENDOR", "ADMIN", name="userrole"),
        existing_nullable=False,
        existing_server_default=sa.text("'CUSTOMER'::userrole"),
    )
    op.drop_column("users", "hashed_password")
    op.alter_column(
        "menus",
        "category",
        existing_type=sa.String(),
        type_=postgresql.ENUM("SHAURMA", "DRINK", "OTHER", name="category"),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
