"""add outbox and order_item indexes

Revision ID: e70e4ca20f9d
Revises: 526539308f98
Create Date: 2026-07-01 16:31:47.886265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e70e4ca20f9d'
down_revision: Union[str, Sequence[str], None] = '526539308f98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index('ix_outbox_events_pending_next_attempt', 'outbox_events', ['next_attempt_at'], unique=False, postgresql_where=sa.text("status = 'PENDING'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outbox_events_pending_next_attempt', table_name='outbox_events', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    # ### end Alembic commands ###
