"""add_deleted_at_to_reviews

Revision ID: f25d1a6c969f
Revises: b1c2d3e4f5a6
Create Date: 2026-04-27 16:50:27.252573

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f25d1a6c969f"
down_revision: Union[str, Sequence[str], None] = "b1c2d3e4f5a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_favorites_user_id"), table_name="favorites")
    op.create_index(op.f("ix_favorites_id"), "favorites", ["id"], unique=False)
    op.drop_constraint(
        op.f("fk_favorites_user_id_users"), "favorites", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_favorites_restaurant_id_restaurants"), "favorites", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_favorites_restaurant_id_restaurants"),
        "favorites",
        "restaurants",
        ["restaurant_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_favorites_user_id_users"), "favorites", "users", ["user_id"], ["id"]
    )
    op.alter_column(
        "promos",
        "expires_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.drop_constraint(op.f("uq_promos_code"), "promos", type_="unique")
    op.create_index(op.f("ix_promos_id"), "promos", ["id"], unique=False)
    op.add_column(
        "reviews", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.drop_index(op.f("ix_working_hours_restaurant_id"), table_name="working_hours")
    op.create_index(op.f("ix_working_hours_id"), "working_hours", ["id"], unique=False)
    op.drop_constraint(
        op.f("fk_working_hours_restaurant_id_restaurants"),
        "working_hours",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_working_hours_restaurant_id_restaurants"),
        "working_hours",
        "restaurants",
        ["restaurant_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_working_hours_restaurant_id_restaurants"),
        "working_hours",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_working_hours_restaurant_id_restaurants"),
        "working_hours",
        "restaurants",
        ["restaurant_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_working_hours_id"), table_name="working_hours")
    op.create_index(
        op.f("ix_working_hours_restaurant_id"),
        "working_hours",
        ["restaurant_id"],
        unique=False,
    )
    op.drop_column("reviews", "deleted_at")
    op.drop_index(op.f("ix_promos_id"), table_name="promos")
    op.create_unique_constraint(
        op.f("uq_promos_code"), "promos", ["code"], postgresql_nulls_not_distinct=False
    )
    op.alter_column(
        "promos",
        "expires_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.drop_constraint(
        op.f("fk_favorites_user_id_users"), "favorites", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_favorites_restaurant_id_restaurants"), "favorites", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_favorites_restaurant_id_restaurants"),
        "favorites",
        "restaurants",
        ["restaurant_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_favorites_user_id_users"),
        "favorites",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_favorites_id"), table_name="favorites")
    op.create_index(
        op.f("ix_favorites_user_id"), "favorites", ["user_id"], unique=False
    )
    # ### end Alembic commands ###
