export const legal = {
  backLabel: "Back",
  terms: {
    title: "Terms of Service",
    body: "## 1. General provisions\n\nThese Terms of Use govern the relationship between the user and the Foodize service when using the food pre-ordering platform, including the Telegram Mini App and the website.\n\nBy using the service, you confirm your agreement with these Terms. If you do not agree with them, please stop using the service.\n\n## 2. Service description\n\nFoodize is a platform for pre-ordering food at food service venues. The service allows users to:\n- browse menus of restaurants and venues;\n- create and pay for orders;\n- receive notifications when an order is ready;\n- leave reviews about venues.\n\nThe service acts as an intermediary between the user and the venue. The venue is responsible for the quality and composition of the dishes.\n\n## 3. Registration and account\n\n3.1. To use the service, you must create an account by providing your name and phone number.\n\n3.2. The user is responsible for keeping their account credentials confidential.\n\n3.3. Creating accounts on behalf of other persons or using inaccurate data is prohibited.\n\n3.4. The service may block an account in the event of a violation of these Terms.\n\n## 4. Placing orders\n\n4.1. An order is considered accepted once it has been confirmed by the venue.\n\n4.2. The service does not guarantee the availability of specific menu items — their availability is determined by the venue.\n\n4.3. Preparation time is an estimate and may differ from the actual time.\n\n4.4. An order may be cancelled until the venue starts working on it. Once preparation has begun, cancellation is not guaranteed.\n\n## 5. Payment\n\n5.1. Payment is made using the methods available in the application at the time of the order.\n\n5.2. Prices are stated in Russian rubles and include VAT where applicable.\n\n5.3. The venue may change dish prices; current prices are shown in the menu at the time of the order.\n\n## 6. Loyalty program\n\n6.1. Bonus points are awarded for completed orders in accordance with the current program rules.\n\n6.2. Points are not funds and cannot be exchanged for cash.\n\n6.3. The service may change the terms of the loyalty program with notice to users.\n\n## 7. Liability\n\n7.1. The service is not liable for the quality and safety of dishes prepared by the venue.\n\n7.2. The service is not liable for technical failures caused by external factors.\n\n7.3. The maximum liability of the service is limited to the amount paid for the order.\n\n## 8. Changes to the terms\n\nThe service may amend these Terms. The current version is published in the application. Continuing to use the service after changes are published constitutes acceptance of them.\n\n## 9. Governing law\n\nThese Terms are governed by the laws of the Russian Federation. Disputes are resolved in accordance with the applicable legislation of the Russian Federation.\n\n## 10. Contacts\n\nFor questions related to the terms of service: **support@foodize.app**",
  },
  privacy: {
    title: "Privacy Policy",
    body: "## 1. General provisions\n\nThis Privacy Policy describes how personal data of Foodize users is collected, used and protected.\n\nPersonal data is processed in accordance with Federal Law No. 152-FZ \"On Personal Data\".\n\nEffective date: June 1, 2026.\n\n## 2. What data we collect\n\n**Data you provide:**\n- first and last name;\n- phone number;\n- email address (if provided);\n- order history and reviews.\n\n**Data collected automatically:**\n- technical device data (model, OS, application version);\n- Telegram Mini App data (Telegram user identifier);\n- logs of actions in the application.\n\n## 3. Purposes of data processing\n\nWe process your data in order to:\n- register and manage your account;\n- process and fulfil orders;\n- send order status notifications;\n- operate the loyalty program;\n- ensure security and prevent fraud;\n- improve the quality of the service.\n\n## 4. Legal grounds for processing\n\n- **Contract:** processing is necessary to fulfil orders.\n- **Consent:** you give consent to data processing when registering.\n- **Legitimate interest:** ensuring the security and operability of the service.\n- **Legislation:** compliance with the requirements of Russian law.\n\n## 5. Transfer of data to third parties\n\n5.1. We pass data to venues only to the extent necessary to fulfil an order (name, phone number).\n\n5.2. We do not sell personal data to third parties.\n\n5.3. Data may be disclosed at the request of authorized bodies in cases provided for by law.\n\n## 6. Data storage\n\n6.1. Data is stored on servers located in the territory of the Russian Federation.\n\n6.2. Account data is stored for the lifetime of the account and for 3 years after its deletion.\n\n6.3. Order history is stored for 5 years in accordance with statutory requirements.\n\n## 7. Security\n\nWe apply technical and organizational data protection measures:\n- encryption in transit (TLS/HTTPS);\n- data access control;\n- regular security audits.\n\n## 8. Your rights\n\nIn accordance with Russian law, you have the right to:\n- obtain information about the data being processed;\n- request correction of inaccurate data;\n- request deletion of data;\n- withdraw consent to processing;\n- file a complaint with Roskomnadzor.\n\nTo exercise your rights, contact: **privacy@foodize.app**\n\n## 9. Cookies and analytics\n\nThe application uses technical cookies to ensure it works properly. Analytics data is collected in anonymized form.\n\n## 10. Changes to the policy\n\nWe may update this Policy. The current version is published in the application together with its effective date.\n\n## 11. Contacts\n\n**Address:** Russia\n**E-mail:** privacy@foodize.app\n**For personal data enquiries:** dpo@foodize.app",
  },
} as const;
